export enum OrderStatus {
    CREATED = 'CREATED',
    CONFIRMED = 'CONFIRMED',
    PREPARATION_STARTED = 'PREPARATION_STARTED',
    READY_TO_PICKUP = 'READY_TO_PICKUP',
    DISPATCHED = 'DISPATCHED',
    COMPLETED = 'COMPLETED',
    CANCELED = 'CANCELED',
    ALL = 'ALL'
  }
  